In [1]:
import numpy as np


1. Representing the data in the given sheet into an appropriate NumPy array so
that we can perform the tasks on it.

In [2]:
Data=np.array([[[8,27,10,22,15,26,15,21,7,26,11,20,6,28],[6,29,8,24,7,32,-13,32,8,23,7,24,15,22],[10,24,15,23,12,25,8,21,9,28,6,22,11,20],[9,31,13,27,14,30,12,29,7,22,6,28,15,32]],[[7,13,9,17,11,23,10,22,8,23,12,33,16,32],[8,12,10,23,14,23,11,23,16,29,12,33,15,23],[7,19,8,23,10,20,13,23,12,25,11,33,18,34],[13,32,8,24,10,33,7,27,8,20,10,33,14,28]],[[6,11,9,23,10,20,11,17,12,23,11,23,17,33],[10,22,12,23,9,23,11,33,13,24,9,33,11,23],[11,23,10,25,9,28,10,23,8,24,9,28,12,33],[3,12,4,15,7,23,9,22,10,24,3,12,11,19]],[[3,12,7,14,8,10,9,15,10,20,12,22,7,25],[3,23,5,22,10,20,3,11,9,10,6,28,11,26],[4,15,4,15,7,16,9,19,10,11,11,22,14,23],[10,20,9,23,7,23,9,23,10,23,11,23,9,23]]])

In [3]:
print(Data)

[[[  8  27  10  22  15  26  15  21   7  26  11  20   6  28]
  [  6  29   8  24   7  32 -13  32   8  23   7  24  15  22]
  [ 10  24  15  23  12  25   8  21   9  28   6  22  11  20]
  [  9  31  13  27  14  30  12  29   7  22   6  28  15  32]]

 [[  7  13   9  17  11  23  10  22   8  23  12  33  16  32]
  [  8  12  10  23  14  23  11  23  16  29  12  33  15  23]
  [  7  19   8  23  10  20  13  23  12  25  11  33  18  34]
  [ 13  32   8  24  10  33   7  27   8  20  10  33  14  28]]

 [[  6  11   9  23  10  20  11  17  12  23  11  23  17  33]
  [ 10  22  12  23   9  23  11  33  13  24   9  33  11  23]
  [ 11  23  10  25   9  28  10  23   8  24   9  28  12  33]
  [  3  12   4  15   7  23   9  22  10  24   3  12  11  19]]

 [[  3  12   7  14   8  10   9  15  10  20  12  22   7  25]
  [  3  23   5  22  10  20   3  11   9  10   6  28  11  26]
  [  4  15   4  15   7  16   9  19  10  11  11  22  14  23]
  [ 10  20   9  23   7  23   9  23  10  23  11  23   9  23]]]


2. Write the dimensions and shape of the NumPy array that you have
created

In [ ]:
print(Data.ndim)
print(Data.shape)

3. Print the daily temperatures for the first week of each month.

In [ ]:
First_week=Data[:, 0,:]
print(First_week)

4. Print the temperatures for Tuesday of each month.

In [ ]:
Tuesday=Data[:,:,2:4]
print(Tuesday)


5. Print only the maximum temperature for all the weekdays of Dec and Feb.

In [ ]:
weekdays=Data[1:4:2,:,0:9:2]
print(weekdays)

6. Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees.

In [52]:
November=Data[0]
min_temp=np.min(November, axis=0)
indices=np.where(min_temp < 8)[0]

[ 0  4  6  8 10 12]


In [ ]:
for i in indices:
    week = i // 7 + 1  # divide by 7 and add 1 to get the week number
    day = i % 7 + 1  # modulo 7 and add 1 to get the day of the week
    print(f"Week {week}, Day {day}: {min_temp[i]}")

7. Print all the weeks in Dec and Jan where the maximum temperature has
crossed a threshold of 20 degrees.