In [1]:
import numpy as np


1. Representing the data in the given sheet into an appropriate NumPy array so
that we can perform the tasks on it.

A. To handle such data sets, first i will visulize it, then i will think of all the task i wanna perform on it and i will create a array on that basis
So i had four months in spreadsheet so i made an array shape of (4,4,14) , First 4 is all 4 months, 2nd 4 is 4 weeks, and 14 is showing min and max temp of days, Now It's easy and handy to perform tasks on it As each 2d array is coantaining months, each 1d array is weeks in assending order

In [2]:
data=np.array([[[8,27,10,22,15,26,15,0,7,22.44,11,20,6,28],[6,29,8,24,7,32,-13,32.199,8,-23,7,24,15,22],[10,24,15,23,12,25,8,-21,9,28,6,22,11,20],[9,31,13,27,14,30,12,29,7,22,6,28,15,32]],[[7,13,9,17,11,23,10,22,8,23,12,33,16,32] ,[8,12,10,23,14,23,11,23,16,29,12,33,15,23],[7,19,8,23,10,20,13,23,12,25,11,33,18,34],[13,32,8,24,10,33,7,27,8,20,10,33,14,28]],[[6,11,9,23,10,20,11,17,12,23,11,23,17,33],[10,22,12,23,9,23,11,33,13,24,9,33,11,23],[11,23,10,25,9,28,10,23,8,24,9,28,12,33],[3,12,4,15,7,23,9,22,10,24,3,12,11,19]],[[3,12,7,14,8,10,9,15,10,20,12,22,7,25],[3,23,5,22,10,20,3,11,9,10,6,28,11,26],[4,15,4,15,7,16,9,19,10,11,11,22,14,23],[10,20,9,23,7,23,9,23,10,23,11,23,9,23]]])

In [3]:
print(data) 

[[[  8.     27.     10.     22.     15.     26.     15.      0.
     7.     22.44   11.     20.      6.     28.   ]
  [  6.     29.      8.     24.      7.     32.    -13.     32.199
     8.    -23.      7.     24.     15.     22.   ]
  [ 10.     24.     15.     23.     12.     25.      8.    -21.
     9.     28.      6.     22.     11.     20.   ]
  [  9.     31.     13.     27.     14.     30.     12.     29.
     7.     22.      6.     28.     15.     32.   ]]

 [[  7.     13.      9.     17.     11.     23.     10.     22.
     8.     23.     12.     33.     16.     32.   ]
  [  8.     12.     10.     23.     14.     23.     11.     23.
    16.     29.     12.     33.     15.     23.   ]
  [  7.     19.      8.     23.     10.     20.     13.     23.
    12.     25.     11.     33.     18.     34.   ]
  [ 13.     32.      8.     24.     10.     33.      7.     27.
     8.     20.     10.     33.     14.     28.   ]]

 [[  6.     11.      9.     23.     10.     20.     11.     17.
 

2. Write the dimensions and shape of the NumPy array that you have
created

In [4]:
print(data.ndim)
print(data.shape)

3
(4, 4, 14)


3. Print the daily temperatures for the first week of each month.

In [5]:
First_week=data[:, 0,:]
print(First_week)

[[ 8.   27.   10.   22.   15.   26.   15.    0.    7.   22.44 11.   20.
   6.   28.  ]
 [ 7.   13.    9.   17.   11.   23.   10.   22.    8.   23.   12.   33.
  16.   32.  ]
 [ 6.   11.    9.   23.   10.   20.   11.   17.   12.   23.   11.   23.
  17.   33.  ]
 [ 3.   12.    7.   14.    8.   10.    9.   15.   10.   20.   12.   22.
   7.   25.  ]]


4. Print the temperatures for Tuesday of each month.

In [6]:
Tuesday=data[:,:,2:4]
print(Tuesday)


[[[10. 22.]
  [ 8. 24.]
  [15. 23.]
  [13. 27.]]

 [[ 9. 17.]
  [10. 23.]
  [ 8. 23.]
  [ 8. 24.]]

 [[ 9. 23.]
  [12. 23.]
  [10. 25.]
  [ 4. 15.]]

 [[ 7. 14.]
  [ 5. 22.]
  [ 4. 15.]
  [ 9. 23.]]]


5. Print only the maximum temperature for all the weekdays of Dec and Feb.

In [7]:
weekdays=data[1:4:2,:,0:9:2]
print(weekdays)

[[[ 7.  9. 11. 10.  8.]
  [ 8. 10. 14. 11. 16.]
  [ 7.  8. 10. 13. 12.]
  [13.  8. 10.  7.  8.]]

 [[ 3.  7.  8.  9. 10.]
  [ 3.  5. 10.  3.  9.]
  [ 4.  4.  7.  9. 10.]
  [10.  9.  7.  9. 10.]]]


6. Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees.

In [8]:
# Access the 2D array for November
november = data[0,:,:]

# Find the minimum temperature for each day in November
min_temps = np.min(november, axis=0)

# Find the indices of the days with minimum temperature less than 8
indices = np.where(min_temps < 8)[0]

# Loop through the indices and print the day and week number
for i in indices:
    week = i // 7 + 1  # divide by 7 and add 1 to get the week number
    day = i % 7 + 1  # modulo 7 and add 1 to get the day of the week
    print(f"Week {week}, Day {day}: {min_temps[i]}")


Week 1, Day 1: 6.0
Week 1, Day 5: 7.0
Week 1, Day 7: -13.0
Week 2, Day 1: -21.0
Week 2, Day 2: 7.0
Week 2, Day 3: -23.0
Week 2, Day 4: 6.0
Week 2, Day 6: 6.0


8. Check if there are any absurd values present in the dataset(like some temp
which should not be present in the data)

In [9]:
absurd_values = data[data <= 0]  # Select all negative temperatures
if len(absurd_values) >= 0:  # Check if there are any absurd values
    print("Absurd values detected:", absurd_values)
else:
    print("No absurd values detected.")


Absurd values detected: [  0. -13. -23. -21.]


9. What strategy would you use to handle such data points?

A. I have provided answer in 1st question

10. Find and print the indexes of all the outlier(unusual) values present in
the above dataset.

In [10]:
# Find the indices of the outlier values 
outlier_indices = np.argwhere(data > 0) # data is > 4 in view of the fact is jaipur's temp doesn't go below 4

# Print the indices
print(outlier_indices)


[[ 0  0  0]
 [ 0  0  1]
 [ 0  0  2]
 [ 0  0  3]
 [ 0  0  4]
 [ 0  0  5]
 [ 0  0  6]
 [ 0  0  8]
 [ 0  0  9]
 [ 0  0 10]
 [ 0  0 11]
 [ 0  0 12]
 [ 0  0 13]
 [ 0  1  0]
 [ 0  1  1]
 [ 0  1  2]
 [ 0  1  3]
 [ 0  1  4]
 [ 0  1  5]
 [ 0  1  7]
 [ 0  1  8]
 [ 0  1 10]
 [ 0  1 11]
 [ 0  1 12]
 [ 0  1 13]
 [ 0  2  0]
 [ 0  2  1]
 [ 0  2  2]
 [ 0  2  3]
 [ 0  2  4]
 [ 0  2  5]
 [ 0  2  6]
 [ 0  2  8]
 [ 0  2  9]
 [ 0  2 10]
 [ 0  2 11]
 [ 0  2 12]
 [ 0  2 13]
 [ 0  3  0]
 [ 0  3  1]
 [ 0  3  2]
 [ 0  3  3]
 [ 0  3  4]
 [ 0  3  5]
 [ 0  3  6]
 [ 0  3  7]
 [ 0  3  8]
 [ 0  3  9]
 [ 0  3 10]
 [ 0  3 11]
 [ 0  3 12]
 [ 0  3 13]
 [ 1  0  0]
 [ 1  0  1]
 [ 1  0  2]
 [ 1  0  3]
 [ 1  0  4]
 [ 1  0  5]
 [ 1  0  6]
 [ 1  0  7]
 [ 1  0  8]
 [ 1  0  9]
 [ 1  0 10]
 [ 1  0 11]
 [ 1  0 12]
 [ 1  0 13]
 [ 1  1  0]
 [ 1  1  1]
 [ 1  1  2]
 [ 1  1  3]
 [ 1  1  4]
 [ 1  1  5]
 [ 1  1  6]
 [ 1  1  7]
 [ 1  1  8]
 [ 1  1  9]
 [ 1  1 10]
 [ 1  1 11]
 [ 1  1 12]
 [ 1  1 13]
 [ 1  2  0]
 [ 1  2  1]
 [ 1  2  2]
 [ 1

11.Replace the outliers with an appropriate value.

In [11]:
outlier = np.where(data < 4) # Finding the index
data[outlier]=8 # replacing outliers with appropriate value
print(data)

[[[ 8.    27.    10.    22.    15.    26.    15.     8.     7.    22.44
   11.    20.     6.    28.   ]
  [ 6.    29.     8.    24.     7.    32.     8.    32.199  8.     8.
    7.    24.    15.    22.   ]
  [10.    24.    15.    23.    12.    25.     8.     8.     9.    28.
    6.    22.    11.    20.   ]
  [ 9.    31.    13.    27.    14.    30.    12.    29.     7.    22.
    6.    28.    15.    32.   ]]

 [[ 7.    13.     9.    17.    11.    23.    10.    22.     8.    23.
   12.    33.    16.    32.   ]
  [ 8.    12.    10.    23.    14.    23.    11.    23.    16.    29.
   12.    33.    15.    23.   ]
  [ 7.    19.     8.    23.    10.    20.    13.    23.    12.    25.
   11.    33.    18.    34.   ]
  [13.    32.     8.    24.    10.    33.     7.    27.     8.    20.
   10.    33.    14.    28.   ]]

 [[ 6.    11.     9.    23.    10.    20.    11.    17.    12.    23.
   11.    23.    17.    33.   ]
  [10.    22.    12.    23.     9.    23.    11.    33.    13.    24.
    9.

12. Find the average max temperature for the winter months in Jaipur.

In [12]:
# Select the elements corresponding to the winter months
winter_months = data[:3]

# Select the maximum temperature for each week
max_temps = winter_months[:, :, 1:14:2]

# Calculate the average maximum temperature for the winter months
avg_max_temp = np.mean(max_temps)

print(f"Average maximum temperature for the winter months in Jaipur: {avg_max_temp:.2f}")


Average maximum temperature for the winter months in Jaipur: 24.03


13. Find the weekly min avg temp for the month of Dec in Jaipur

In [13]:
# Select the elements corresponding to the month of December
december = data[1]

# Select the minimum temperature for each week
min_temps = december[:, 0:14:2]

# Calculate the average minimum temperature for each week
avg_min_temps = np.mean(min_temps, axis=0)

print(f"Average minimum temperatures for each week in December in Jaipur: {avg_min_temps}")


Average minimum temperatures for each week in December in Jaipur: [ 8.75  8.75 11.25 10.25 11.   11.25 15.75]


14. Find the overall avg temp for the months Dec and Jan

In [14]:
# Select the elements corresponding to the months of December and January
dec_jan = data[1:3]

# Flatten the array to a 1D array
flat_array = dec_jan.flatten()

# Calculate the average temperature for the months of December and January
avg_temp = np.mean(flat_array)

print(f"Overall average temperature for the months of December and January: {avg_temp:.2f}")


Overall average temperature for the months of December and January: 17.23


15. Find the least temp experienced by the city in the month of Dec and
Jan. Also print the exact date( Day/Week/Month) for the same.

In [15]:
# Select the elements corresponding to the months of December and January
dec_jan = data[1:3]

# Flatten the array to a 1D array
flat_array = dec_jan.flatten()

# Find the minimum temperature
min_temp = np.min(flat_array)

: 